//! `mqtt-controller` binary entry point. Two subcommands:
//!
//!   * `provision` — one-shot reconciler. Replaces `hue-setup`.
//!   * `daemon`    — long-running runtime controller. Replaces the bento
//!                   `mqtt-automation` systemd service.

use std::path::PathBuf;
use std::sync::Arc;
use std::time::Duration;

use anyhow::{Context, Result};
use clap::{Parser, Subcommand};
use tracing_subscriber::layer::SubscriberExt;
use tracing_subscriber::util::SubscriberInitExt;
use tracing_subscriber::{EnvFilter, Layer};

use mqtt_controller::config::Config;
use mqtt_controller::mqtt::MqttConfig;
use mqtt_controller::provision::{ProvisionOptions, reconcile};
use mqtt_controller::time::SystemClock;
use mqtt_controller::web::decision_capture::DecisionCaptureLayer;

#[derive(Debug, Parser)]
#[command(
    name = "mqtt-controller",
    version,
    about = "Unified zigbee2mqtt provisioner and runtime controller"
)]
struct Cli {
    /// Verbose action logging. When set, every command the daemon
    /// publishes to MQTT (and every state-machine branch that decides
    /// to publish one) is logged at info level with a human-readable
    /// reason. Without this flag the daemon only emits
    /// warnings and errors.
    ///
    /// Equivalent to setting `RUST_LOG=mqtt_controller=info`. The env
    /// var still wins if set explicitly.
    #[arg(long, short = 'v', global = true)]
    verbose: bool,

    #[command(subcommand)]
    command: Command,
}

#[derive(Debug, Subcommand)]
enum Command {
    /// Reconcile z2m groups, members, scenes, and per-device options
    /// against the JSON config. One-shot. Replaces `hue-setup`.
    Provision(ProvisionArgs),

    /// Long-running runtime controller. Subscribes to button/motion/group
    /// MQTT events, runs the per-zone state machine, publishes commands.
    /// Replaces the bento `mqtt-automation` service.
    Daemon(DaemonArgs),
}

#[derive(Debug, Parser)]
struct CommonMqttArgs {
    /// Path to the unified JSON config (generated by Nix from
    /// `defineRooms`).
    #[arg(long)]
    config: PathBuf,

    #[arg(long, default_value = "localhost")]
    mqtt_host: String,

    #[arg(long, default_value_t = 1883)]
    mqtt_port: u16,

    #[arg(long, default_value = "mqtt")]
    mqtt_user: String,

    /// File containing the MQTT password (one line, trailing whitespace
    /// stripped).
    #[arg(long)]
    mqtt_password_file: PathBuf,
}

#[derive(Debug, Parser)]
struct ProvisionArgs {
    #[command(flatten)]
    mqtt: CommonMqttArgs,

    /// Print what would be done without publishing anything.
    #[arg(long)]
    dry_run: bool,

    /// Rewrite every per-device option unconditionally, bypassing the
    /// dedup check against z2m's state cache. Use when a device is
    /// known to report a stale value (e.g. Sonoff inching/overload
    /// settings that show DISABLE while the hardware still has the
    /// setting active).
    #[arg(long)]
    force_options: bool,

    /// Remove members and groups present in z2m but not in the config.
    /// Default is additive-only.
    #[arg(long)]
    prune: bool,

    /// MQTT operation timeout, seconds.
    #[arg(long, default_value_t = 5.0)]
    timeout: f64,

    /// How many times to retry the initial bridge/groups + bridge/devices
    /// fetch on early-boot races (z2m up but inventory not yet published).
    #[arg(long, default_value_t = 12)]
    fetch_attempts: u32,

    /// Delay between fetch retries, seconds.
    #[arg(long, default_value_t = 5.0)]
    fetch_retry_seconds: f64,

    /// z2m WebSocket API URL for bulk device state fetch.
    /// Example: ws://localhost:8080/api
    #[arg(long)]
    z2m_ws_url: String,
}

#[derive(Debug, Parser)]
struct DaemonArgs {
    #[command(flatten)]
    mqtt: CommonMqttArgs,

    /// z2m WebSocket API URL for the startup state seed.
    /// Example: `ws://localhost:8080/api`. Same endpoint the provisioner
    /// uses; the daemon now calls it once on startup to prime every
    /// entity's actual state in one round-trip (no more per-group `/get`
    /// cascade).
    #[arg(long)]
    z2m_ws_url: String,

    /// `zwave-js-server` WebSocket URL for the startup state seed.
    /// Example: `ws://localhost:3000`. ZJS-UI embeds `zwave-js-server`
    /// on this port; the daemon queries its native JSON-RPC protocol
    /// once on startup to prime every z-wave plug's actual state.
    /// Optional: omit to skip the z-wave seed (state will populate
    /// from live MQTT publishes instead).
    #[arg(long)]
    zwave_ws_url: Option<String>,

    /// IANA timezone name for time-of-day slot dispatch (e.g.
    /// "Europe/Amsterdam"). Defaults to the system's TZ environment
    /// variable, falling back to UTC.
    #[arg(long)]
    timezone: Option<String>,

    /// Port for the web dashboard HTTP/WebSocket server. If omitted, no
    /// web server starts and the daemon runs MQTT-only as before.
    #[arg(long)]
    web_port: Option<u16>,

    /// Directory containing the built dashboard assets. Required with --web-port.
    #[arg(long)]
    web_assets_dir: Option<PathBuf>,
    /// Persistent 24-hour telemetry history database. Required with --web-port.
    #[arg(long)]
    web_history_db: Option<PathBuf>,
}

/// Initialize the tracing subscriber.
///
/// Precedence (highest first):
///   1. `RUST_LOG` env var (always wins if set)
///   2. `--verbose` CLI flag → `mqtt_controller=info` (action logging on)
///   3. default → `mqtt_controller=warn` (only warnings + errors)
///
/// When `web_enabled` is true, installs a [`DecisionCaptureLayer`]
/// alongside the fmt layer so that `start_capture()`/`drain_capture()`
/// can collect decision tracing during `handle_event`.
fn init_tracing(verbose: bool, web_enabled: bool) {
    let filter = EnvFilter::try_from_default_env().unwrap_or_else(|_| {
        if verbose {
            EnvFilter::new("mqtt_controller=info")
        } else {
            EnvFilter::new("mqtt_controller=warn")
        }
    });
    let fmt_layer = tracing_subscriber::fmt::layer().with_filter(filter);

    if web_enabled {
        tracing_subscriber::registry()
            .with(fmt_layer)
            .with(DecisionCaptureLayer)
            .init();
    } else {
        tracing_subscriber::registry()
            .with(fmt_layer)
            .init();
    }
}

fn main() -> Result<()> {
    let cli = Cli::parse();
    let web_enabled = matches!(&cli.command, Command::Daemon(d) if d.web_port.is_some());
    init_tracing(cli.verbose, web_enabled);

    let runtime = tokio::runtime::Builder::new_multi_thread()
        .enable_all()
        .build()
        .context("building tokio runtime")?;

    runtime.block_on(async {
        match cli.command {
            Command::Provision(args) => run_provision(args).await,
            Command::Daemon(args) => run_daemon(args).await,
        }
    })
}

fn read_password(path: &PathBuf) -> Result<String> {
    let raw = std::fs::read_to_string(path)
        .with_context(|| format!("reading mqtt password file {}", path.display()))?;
    Ok(raw.trim().to_string())
}

fn build_mqtt_config(args: &CommonMqttArgs, role: &str) -> Result<MqttConfig> {
    let password = read_password(&args.mqtt_password_file)?;
    let client_id = format!("mqtt-controller-{role}-{}", uuid::Uuid::new_v4());
    Ok(MqttConfig::new(
        args.mqtt_host.clone(),
        args.mqtt_port,
        args.mqtt_user.clone(),
        password,
        client_id,
    ))
}

async fn run_provision(args: ProvisionArgs) -> Result<()> {
    let config = Config::load_from_path(&args.mqtt.config)
        .with_context(|| format!("loading config from {}", args.mqtt.config.display()))?;
    tracing::info!(
        rooms = config.rooms.len(),
        devices = config.devices.len(),
        dry_run = args.dry_run,
        force_options = args.force_options,
        prune = args.prune,
        "loaded config (provision)"
    );

    let mqtt = build_mqtt_config(&args.mqtt, "provision")?;
    let options = ProvisionOptions {
        dry_run: args.dry_run,
        force_options: args.force_options,
        prune: args.prune,
        timeout: Duration::from_secs_f64(args.timeout),
        settle: Duration::from_millis(400),
        fetch_attempts: args.fetch_attempts,
        fetch_retry: Duration::from_secs_f64(args.fetch_retry_seconds),
    };

    let summary = reconcile(&config, mqtt, &args.z2m_ws_url, options)
        .await
        .context("reconciling z2m state")?;

    let action_word = if args.dry_run { "would touch" } else { "touched" };
    tracing::info!(
        touched = summary.touched,
        skipped = summary.skipped,
        "done; {action_word} {} item(s)",
        summary.touched
    );
    Ok(())
}

async fn run_daemon(args: DaemonArgs) -> Result<()> {
    let config = Config::load_from_path(&args.mqtt.config)
        .with_context(|| format!("loading config from {}", args.mqtt.config.display()))?;
    tracing::info!(rooms = config.rooms.len(), "loaded config (daemon)");

    let timezone = resolve_timezone(args.timezone.as_deref())?;
    let clock = Arc::new(SystemClock::new(timezone));
    let mqtt = build_mqtt_config(&args.mqtt, "daemon")?;

    let web = if let Some(port) = args.web_port {
        let assets_dir = args
            .web_assets_dir
            .context("--web-assets-dir is required when --web-port is set")?;
        anyhow::ensure!(
            assets_dir.is_dir(),
            "--web-assets-dir {}: not a directory",
            assets_dir.display()
        );

        let (ws_cmd_tx, ws_cmd_rx) = tokio::sync::mpsc::channel(64);
        let (broadcast_tx, _) = tokio::sync::broadcast::channel(256);
        let history_path = args.web_history_db.context("--web-history-db is required when --web-port is set")?;
        let history = mqtt_controller::web::history::HeatingHistory::open(&history_path).await
            .with_context(|| format!("opening telemetry history {}", history_path.display()))?;
        let _history_sampler = history.spawn_sampler(ws_cmd_tx.clone());

        // Audit log is opt-in via the `audit_log` config block. Only
        // enabled alongside the web subsystem because the persisted
        // history is consumed by the per-entity popup; without web
        // there is no consumer.
        let (audit_writer, audit_db) = match config.audit_log.as_ref() {
            Some(audit_cfg) => match mqtt_controller::audit::open(&audit_cfg.path).await {
                Ok(db) => {
                    let (writer, _writer_handle) =
                        mqtt_controller::audit::spawn_writer(db.clone(), audit_cfg.clone());
                    let _retention_handle =
                        mqtt_controller::audit::spawn_retention(db.clone(), audit_cfg.clone());
                    tracing::info!(
                        path = %audit_cfg.path.display(),
                        retention_days = audit_cfg.retention_days,
                        per_entity_max_rows = audit_cfg.per_entity_max_rows,
                        "audit log enabled"
                    );
                    (Some(writer), Some(db))
                }
                Err(e) => {
                    tracing::error!(
                        error = %e,
                        path = %audit_cfg.path.display(),
                        "failed to open audit log; continuing without persistence"
                    );
                    (None, None)
                }
            },
            None => (None, None),
        };

        let addr = std::net::SocketAddr::from(([0, 0, 0, 0], port));
        let (_bound_addr, _server_handle) =
            mqtt_controller::web::bind_and_start_web_server(
                addr,
                ws_cmd_tx,
                broadcast_tx.clone(),
                assets_dir,
                audit_db,
                history,
            )
            .await
            .with_context(|| format!("binding web server on {addr}"))?;

        Some(mqtt_controller::web::WebHandle {
            ws_cmd_rx,
            broadcast_tx,
            audit_writer,
        })
    } else {
        None
    };

    mqtt_controller::daemon::run(
        config,
        mqtt,
        Some(args.z2m_ws_url),
        args.zwave_ws_url,
        clock,
        web,
    )
    .await
}

fn resolve_timezone(explicit: Option<&str>) -> Result<chrono_tz::Tz> {
    let name = explicit
        .map(String::from)
        .or_else(|| std::env::var("TZ").ok())
        .unwrap_or_else(|| "UTC".to_string());
    name.parse::<chrono_tz::Tz>()
        .map_err(|e| anyhow::anyhow!("invalid timezone {name:?}: {e}"))
}
