import { expect, test } from '@playwright/test';

test('light schedule editor saves slot overrides and restores defaults from the dialog', async ({ page }) => {
  await page.goto('/#lights');
  const room = page.getByRole('article', { name: 'Ensuite', exact: true });
  await expect(room.getByRole('button', { name: 'Recall scene 2 in Ensuite' })).toBeVisible();
  await room.getByRole('button', { name: 'Edit schedule' }).click();
  const editor = page.getByRole('dialog', { name: 'Schedule for Ensuite' });
  await expect(editor.getByRole('textbox', { name: 'Name of slot 1' })).toHaveValue('morning');
  await expect(editor.getByRole('textbox', { name: 'Name of slot 3' })).toHaveValue('evening');
  await expect(editor.getByRole('button', { name: 'Save schedule' })).toBeDisabled();
  await editor.getByRole('button', { name: 'Remove scene 2 from Evening' }).click();
  await editor.getByLabel('Evening end').fill('sunset+01:00');
  await expect(editor.getByRole('button', { name: 'Save schedule' })).toBeEnabled();
  await editor.getByLabel('Night start').fill('sun down');
  await expect(editor.getByRole('status')).toContainText('Night: times are HH:MM');
  await expect(editor.getByRole('button', { name: 'Save schedule' })).toBeDisabled();
  await editor.getByLabel('Night start').fill('sunset+01:00');
  await editor.getByRole('button', { name: 'Save schedule' }).click();
  await expect(editor).not.toBeVisible();
  await expect(room.getByRole('button', { name: 'Edit schedule · Override active' })).toBeVisible();
  await expect(room.getByRole('button', { name: 'Recall scene 2 in Ensuite' })).toHaveCount(0);
  await expect(room.getByRole('button', { name: 'Recall scene 3 in Ensuite' })).toBeVisible();
  await expect(room.getByRole('status')).toHaveCount(0);

  await room.getByRole('button', { name: /Override active/ }).click();
  await expect(editor.getByRole('group', { name: 'Evening scenes' })).toContainText('1. 3 · Dim');
  await editor.getByRole('button', { name: 'Restore defaults' }).click();
  await expect(editor).not.toBeVisible();
  await expect(room.getByRole('button', { name: 'Edit schedule', exact: true })).toBeVisible();
  await expect(room.getByRole('button', { name: 'Recall scene 2 in Ensuite' })).toBeVisible();
});

test('light slots can be split, added and removed with full-day coverage checked', async ({ page }) => {
  await page.goto('/#lights');
  const room = page.getByRole('article', { name: 'Ensuite', exact: true });
  await room.getByRole('button', { name: 'Edit schedule' }).click();
  const editor = page.getByRole('dialog', { name: 'Schedule for Ensuite' });
  await editor.getByRole('button', { name: 'Split slot Day' }).click();
  await expect(editor.getByRole('textbox', { name: 'Name of slot 3' })).toHaveValue('day-2');
  await expect(editor.getByLabel('Day end')).toHaveValue('12:00');
  await expect(editor.getByLabel('Day 2 start')).toHaveValue('12:00');
  await expect(editor.getByRole('button', { name: 'Save schedule' })).toBeEnabled();
  await editor.getByLabel('Day 2 end').fill('17:00');
  await expect(editor.getByRole('status')).toHaveText('Slots leave 17:00–18:00 uncovered.');
  await editor.getByLabel('Day 2 end').fill('19:00');
  await expect(editor.getByRole('status')).toHaveText('18:00 is covered by more than one slot.');
  await editor.getByRole('button', { name: 'Remove slot Day 2' }).click();
  await editor.getByLabel('Day end').fill('18:00');
  await expect(editor.getByRole('status')).toHaveCount(0);
  await editor.getByRole('button', { name: 'Add slot' }).click();
  await expect(editor.getByRole('status')).toHaveText('Every slot needs a name.');
  await editor.getByRole('textbox', { name: 'Name of slot 5' }).fill('day');
  await expect(editor.getByRole('status')).toHaveText('Slot names must be unique.');
  await editor.getByRole('textbox', { name: 'Name of slot 5' }).fill('dusk');
  await expect(editor.getByRole('status')).toContainText('Dusk: times are HH:MM');
  await editor.getByLabel('Dusk start').fill('17:00');
  await editor.getByLabel('Dusk end').fill('18:00');
  await editor.getByLabel('Day end').fill('17:00');
  await expect(editor.getByRole('status')).toHaveCount(0);
  await editor.getByRole('button', { name: 'Save schedule' }).click();
  await expect(room.getByRole('button', { name: 'Edit schedule · Override active' })).toBeVisible();
  await room.getByRole('button', { name: /Override active/ }).click();
  await expect(editor.getByRole('textbox', { name: 'Name of slot 3' })).toHaveValue('dusk');
});

test('switch steps stagger the lights of a slot and are saved with the schedule', async ({ page }) => {
  await page.goto('/#lights');
  const room = page.getByRole('article', { name: 'Ensuite', exact: true });
  await room.getByRole('button', { name: 'Edit schedule' }).click();
  const editor = page.getByRole('dialog', { name: 'Schedule for Ensuite' });
  const steps = editor.getByRole('group', { name: 'Evening switch steps' });
  await expect(steps.getByRole('button', { name: 'Ensuite wall in Evening step 1' })).toHaveAttribute('aria-pressed', 'true');
  await expect(steps.getByRole('button', { name: 'Ensuite ceiling in Evening step 1' })).toHaveAttribute('aria-pressed', 'false');
  await expect(editor.getByRole('group', { name: 'Day switch steps' })).toContainText('Each press cycles the whole group');
  await steps.getByRole('button', { name: 'Ensuite wall in Evening step 1' }).click();
  await expect(editor.getByRole('status')).toHaveText('Evening: every switch step needs at least one light.');
  await steps.getByRole('button', { name: 'Ensuite ceiling in Evening step 1' }).click();
  await steps.getByRole('button', { name: 'Add step' }).click();
  await steps.getByRole('combobox', { name: 'Scene of Evening step 3' }).selectOption('1');
  await editor.getByRole('button', { name: 'Save schedule' }).click();
  await expect(room.getByRole('button', { name: 'Edit schedule · Override active' })).toBeVisible();
  await room.getByRole('button', { name: /Override active/ }).click();
  await expect(steps.getByRole('button', { name: 'Ensuite ceiling in Evening step 1' })).toHaveAttribute('aria-pressed', 'true');
  await expect(steps.getByRole('button', { name: 'Ensuite wall in Evening step 1' })).toHaveAttribute('aria-pressed', 'false');
  await expect(steps.getByRole('combobox', { name: 'Scene of Evening step 3' })).toHaveValue('1');
  await steps.getByRole('button', { name: 'Remove Evening step 3' }).click();
  await steps.getByRole('button', { name: 'Remove Evening step 2' }).click();
  await steps.getByRole('button', { name: 'Remove Evening step 1' }).click();
  await expect(steps).toContainText('Each press cycles the whole group');
  await expect(editor.getByRole('button', { name: 'Save schedule' })).toBeEnabled();
});

test('motion schedule editor keeps slot names and requires scenes', async ({ page }) => {
  await page.goto('/#lights');
  const room = page.getByRole('article', { name: 'Ensuite', exact: true });
  await room.getByText('Lights & automation').click();
  await room.getByRole('button', { name: 'Edit motion schedule' }).click();
  const editor = page.getByRole('dialog', { name: 'Motion schedule for Ensuite motion' });
  await expect(editor.getByRole('textbox', { name: /Name of slot/ })).toHaveCount(0);
  await expect(editor.getByRole('button', { name: 'Add slot' })).toHaveCount(0);
  await editor.getByRole('button', { name: 'Remove scene 1 from Day' }).click();
  await expect(editor.getByRole('status')).toHaveText('Day needs at least one scene.');
  await expect(editor.getByRole('button', { name: 'Save schedule' })).toBeDisabled();
  await editor.getByRole('combobox', { name: 'Add scene to Day' }).selectOption('2');
  await editor.getByRole('button', { name: 'Save schedule' }).click();
  await expect(room.getByRole('button', { name: 'Edit motion schedule · Override active' })).toBeVisible();
  await room.getByRole('button', { name: 'Edit motion schedule · Override active' }).click();
  await editor.getByRole('button', { name: 'Restore defaults' }).click();
  await expect(room.getByRole('button', { name: 'Edit motion schedule', exact: true })).toBeVisible();
});

test('timed actions and plug rules are edited in the schedule dialogs', async ({ page }) => {
  await page.goto('/#lights');
  const room = page.getByRole('article', { name: 'Ensuite', exact: true });
  await room.getByRole('button', { name: 'Edit schedule' }).click();
  const editor = page.getByRole('dialog', { name: 'Schedule for Ensuite' });
  const time = editor.getByLabel('Time for Ensuite night off');
  await time.fill('25:00h');
  await expect(editor.getByRole('button', { name: 'Save schedule' })).toBeDisabled();
  await time.fill('sunset-00:30');
  await editor.getByRole('button', { name: 'Save schedule' }).click();
  await room.getByText('Lights & automation').click();
  await expect(room.getByText('Ensuite night off · turn off → Ensuite at sunset-00:30 · Override active')).toBeVisible();
  await expect(room.getByRole('button', { name: 'Edit schedule · Override active' })).toBeVisible();
  await room.getByRole('button', { name: /Override active/ }).click();
  await editor.getByRole('button', { name: 'Restore defaults' }).click();
  await expect(room.getByText('Ensuite night off · turn off → Ensuite at 23:30')).toBeVisible();

  await page.goto('/#plugs');
  const plug = page.getByRole('article', { name: '3d printer' });
  await plug.getByRole('button', { name: 'Edit schedule' }).click();
  const plugEditor = page.getByRole('dialog', { name: 'Schedule for 3d printer' });
  await plugEditor.getByRole('spinbutton', { name: 'Threshold for Printer idle' }).fill('2.5');
  await plugEditor.getByRole('spinbutton', { name: 'Holdoff for Printer idle' }).fill('0');
  await expect(plugEditor.getByRole('status')).toHaveText('Printer idle needs a positive watt threshold and a whole number of seconds.');
  await plugEditor.getByRole('spinbutton', { name: 'Holdoff for Printer idle' }).fill('45');
  await plugEditor.getByLabel('Time for Printer morning').fill('07:45');
  await plugEditor.getByRole('button', { name: 'Save schedule' }).click();
  await expect(plug.getByRole('button', { name: 'Edit schedule · Override active' })).toBeVisible();
  await plug.getByText('Automation & device').click();
  await expect(plug.getByText('Turns off below 2.5 W for 45s · Override active.')).toBeVisible();
  await expect(plug.getByText('Printer morning · turn on → Printer at 07:45 · Override active')).toBeVisible();
  await expect(plug.getByRole('status')).toHaveCount(0);
  await plug.getByRole('button', { name: /Override active/ }).click();
  await plugEditor.getByRole('button', { name: 'Restore defaults' }).click();
  await expect(plug.getByText('Turns off below 10 W for 2m.')).toBeVisible();
  await expect(plug.getByText('Printer morning · turn on → Printer at 07:00')).toBeVisible();
  await expect(plug.getByRole('button', { name: 'Edit schedule', exact: true })).toBeVisible();
});
